defaults:
  - scope:
      path: "docs/README.md"
    values:
      lang: "en"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/"
  - scope:
      path: "docs/cs/README.md"
    values:
      lang: "cs"
      title: "O aplikaci - OSM Apps Catalog"
      description: "Poznávejte svět kreativním, produktivním a nečekaným způsobem."
      base: "/cs/"
  - scope:
      path: "docs/de/README.md"
    values:
      lang: "de"
      title: "Über - OSM Apps Katalog"
      description: "Erleben Sie die Welt auf kreative, produktive und unerwartete Weise."
      base: "/de/"
  - scope:
      path: "docs/el/README.md"
    values:
      lang: "el"
      title: "About - OSM Apps Catalog"
      description: "Ζήστε τον κόσμο με δημιουργικό, παραγωγικό και απρόσμενο τρόπο."
      base: "/el/"
  - scope:
      path: "docs/es/README.md"
    values:
      lang: "es"
      title: "Acerca de - OSM Apps Catalog"
      description: "Experimente el mundo de maneras creativas, productivas e inesperadas."
      base: "/es/"
  - scope:
      path: "docs/et/README.md"
    values:
      lang: "et"
      title: "Veebirakenduse teave - OSM Apps Catalog"
      description: "Koge maailma loomingulisel, tulemusrikkal ja ootamatul viisil."
      base: "/et/"
  - scope:
      path: "docs/fr/README.md"
    values:
      lang: "fr"
      title: "À propos - OSM Apps Catalog"
      description: "Découvrez le monde d’une manière créative, productive et inattendue."
      base: "/fr/"
  - scope:
      path: "docs/hu/README.md"
    values:
      lang: "hu"
      title: "Névjegy - OSM Apps Catalog"
      description: "Tapasztald meg a világot kreatív, produktív és váratlan módokon."
      base: "/hu/"
  - scope:
      path: "docs/id/README.md"
    values:
      lang: "id"
      title: "Tentang - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/id/"
  - scope:
      path: "docs/it/README.md"
    values:
      lang: "it"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/it/"
  - scope:
      path: "docs/ja/README.md"
    values:
      lang: "ja"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/ja/"
  - scope:
      path: "docs/ko/README.md"
    values:
      lang: "ko"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/ko/"
  - scope:
      path: "docs/nb_NO/README.md"
    values:
      lang: "no"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/no/"
  - scope:
      path: "docs/pl/README.md"
    values:
      lang: "pl"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/pl/"
  - scope:
      path: "docs/pt/README.md"
    values:
      lang: "pt"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/pt/"
  - scope:
      path: "docs/ru/README.md"
    values:
      lang: "ru"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/ru/"
  - scope:
      path: "docs/sv/README.md"
    values:
      lang: "sv"
      title: "Om - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/sv/"
  - scope:
      path: "docs/ta/README.md"
    values:
      lang: "ta"
      title: "பற்றி - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/ta/"
  - scope:
      path: "docs/tr/README.md"
    values:
      lang: "tr"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/tr/"
  - scope:
      path: "docs/uk/README.md"
    values:
      lang: "uk"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/uk/"
  - scope:
      path: "docs/zh_Hant/README.md"
    values:
      lang: "zh"
      title: "About - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/zh/"
  - scope:
      path: "docs/zh-Hans/README.md"
    values:
      lang: "zh-Hans"
      title: "關於 - OSM Apps Catalog"
      description: "There isn't just one, there are thousands."
      base: "/zh-hans/"
