name: Collect osm apps

description: test

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Jeden Tag um Mitternacht

permissions:
  contents: write

jobs:
  collect-osm-apps-action:
    name: Collect osm apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Collect osm apps
        id: collect-osm-apps-action
        uses: ./actions/collect-osm-apps
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}

