name: Collect OSM Apps

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Jeden Tag um Mitternacht

permissions:
  contents: write

jobs:
  collect-osm-apps-action:
    name: Collect OSM Apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Collect OSM Apps
        id: collect-osm-apps-action
        uses: ./github-actions/collect-osm-apps
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}

